# Generated by Django 5.0.1 on 2026-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(help_text='Titre du produit en français', max_length=200, verbose_name='Titre (Français)')),
                ('titre_en', models.CharField(blank=True, help_text='Titre du produit en anglais', max_length=200, verbose_name='Titre (Anglais)')),
                ('titre_ar', models.CharField(blank=True, help_text='Titre du produit en arabe', max_length=200, verbose_name='Titre (Arabe)')),
                ('image_couverture', models.ImageField(blank=True, help_text='Image principale du produit', null=True, upload_to='produits/couvertures/', verbose_name='Image de couverture')),
                ('description_fr', models.TextField(help_text='Description détaillée du produit en français', verbose_name='Description (Français)')),
                ('description_en', models.TextField(blank=True, help_text='Description détaillée du produit en anglais', verbose_name='Description (Anglais)')),
                ('description_ar', models.TextField(blank=True, help_text='Description détaillée du produit en arabe', verbose_name='Description (Arabe)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Désignez si ce produit est actif ou non', verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Produit / Équipement',
                'verbose_name_plural': 'Produits / Équipements',
                'ordering': ['ordre', 'titre_fr'],
                'indexes': [models.Index(fields=['ordre', 'actif'], name='produit_pro_ordre_06c917_idx'), models.Index(fields=['titre_fr'], name='produit_pro_titre_f_c74783_idx')],
            },
        ),
    ]
