# Generated by Django 5.0.1 on 2026-01-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0002_alter_partenaire_actif_alter_partenaire_logo_and_more'),
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='partenaires',
            field=models.ManyToManyField(blank=True, help_text='Partenaires associés à ce produit', related_name='produits', to='partenaire.partenaire', verbose_name='Partenaires'),
        ),
    ]
