# Generated by Django 5.0.1 on 2026-01-15 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='actif',
            field=models.BooleanField(default=True, help_text='Désignez si ce partenaire est actif ou non', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du partenaire', null=True, upload_to='partenaires/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(help_text='Nom complet du partenaire', max_length=200, verbose_name='Nom du partenaire'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='url_site_web',
            field=models.URLField(help_text='URL complète du site web du partenaire', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL du site web'),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['nom'], name='partenaire__nom_05d885_idx'),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['actif'], name='partenaire__actif_6d31a8_idx'),
        ),
    ]
