# Generated by Django 5.0.1 on 2026-01-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0002_alter_partenaire_actif_alter_partenaire_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(help_text='Titre de la famille en français', max_length=200, verbose_name='Titre (Français)')),
                ('titre_en', models.CharField(blank=True, help_text='Titre de la famille en anglais', max_length=200, verbose_name='Titre (Anglais)')),
                ('titre_ar', models.CharField(blank=True, help_text='Titre de la famille en arabe', max_length=200, verbose_name='Titre (Arabe)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Désignez si cette famille est active ou non', verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
                ('partenaires', models.ManyToManyField(blank=True, help_text='Partenaires associés à cette famille', related_name='familles', to='partenaire.partenaire', verbose_name='Partenaires')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['ordre', 'titre_fr'],
            },
        ),
        migrations.CreateModel(
            name='SousFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(help_text='Titre de la sous-famille en français', max_length=200, verbose_name='Titre (Français)')),
                ('titre_en', models.CharField(blank=True, help_text='Titre de la sous-famille en anglais', max_length=200, verbose_name='Titre (Anglais)')),
                ('titre_ar', models.CharField(blank=True, help_text='Titre de la sous-famille en arabe', max_length=200, verbose_name='Titre (Arabe)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Désignez si cette sous-famille est active ou non', verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
                ('famille', models.ForeignKey(help_text='Famille parente de cette sous-famille', on_delete=django.db.models.deletion.CASCADE, related_name='sous_familles', to='partenaire.famille', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Sous-famille',
                'verbose_name_plural': 'Sous-familles',
                'ordering': ['ordre', 'titre_fr'],
            },
        ),
        migrations.AddIndex(
            model_name='famille',
            index=models.Index(fields=['ordre', 'actif'], name='partenaire__ordre_dfc159_idx'),
        ),
        migrations.AddIndex(
            model_name='famille',
            index=models.Index(fields=['titre_fr'], name='partenaire__titre_f_25dd9c_idx'),
        ),
        migrations.AddIndex(
            model_name='sousfamille',
            index=models.Index(fields=['famille', 'ordre', 'actif'], name='partenaire__famille_b8ffce_idx'),
        ),
        migrations.AddIndex(
            model_name='sousfamille',
            index=models.Index(fields=['titre_fr'], name='partenaire__titre_f_10c286_idx'),
        ),
    ]
