# Generated by Django 5.0.1 on 2026-01-15 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0003_famille_sousfamille_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du produit fournisseur', max_length=200, verbose_name='Nom du produit')),
                ('image', models.ImageField(blank=True, help_text='Image du produit fournisseur', null=True, upload_to='produits_fournisseur/images/', verbose_name='Image')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Désignez si ce produit est actif ou non', verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
                ('sous_famille', models.ForeignKey(help_text='Sous-famille parente de ce produit', on_delete=django.db.models.deletion.CASCADE, related_name='produits_fournisseur', to='partenaire.sousfamille', verbose_name='Sous-famille')),
            ],
            options={
                'verbose_name': 'Produit Fournisseur',
                'verbose_name_plural': 'Produits Fournisseurs',
                'ordering': ['ordre', 'nom'],
                'indexes': [models.Index(fields=['sous_famille', 'ordre', 'actif'], name='partenaire__sous_fa_6210db_idx'), models.Index(fields=['nom'], name='partenaire__nom_f2d3b9_idx')],
            },
        ),
    ]
