# Generated by Django 5.0.1 on 2026-01-16 00:10

import django.db.models.deletion
import partenaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0004_produitfournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom ou titre du catalogue (optionnel)', max_length=200, null=True, verbose_name='Nom du catalogue')),
                ('fichier_pdf', models.FileField(help_text='Fichier PDF du catalogue', upload_to='catalogues/pdf/', validators=[partenaire.models.validate_pdf_file], verbose_name='Fichier PDF')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Désignez si ce catalogue est actif ou non', verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
                ('produit_fournisseur', models.ForeignKey(help_text='Produit fournisseur parent de ce catalogue', on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='partenaire.produitfournisseur', verbose_name='Produit Fournisseur')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
                'ordering': ['ordre', 'nom', 'date_creation'],
                'indexes': [models.Index(fields=['produit_fournisseur', 'ordre', 'actif'], name='partenaire__produit_13a300_idx'), models.Index(fields=['nom'], name='partenaire__nom_4e1b43_idx')],
            },
        ),
    ]
